update application_customuser set username2 = 'admin', userlanguage = 'English', usertype = 'Individual' where is_superuser = 1;
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('sk','Slovak','sk','スロバキア語','Slovak','Eslovaco','斯洛伐克文','斯洛伐克文','슬로바키아어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('uk','Ukrainian','ua','ウクライナ語','Ukrainian','Ucranio','烏克蘭','乌克兰','우크라이나어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('sr','Serbian','sr','セルビア語','Serbian','Serbio','塞爾維亞','塞尔维亚','세르비아어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('ar','Arabic','','アラビア語','Arabic','Arábica','阿拉伯','阿拉伯','아랍어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('de','German','de','ドイツ語','German','Alemán','德語','德语','독일','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('en','English','en','英語','English','Inglés','英語','英语','영어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('es','Spanish (Spain)','es','スペイン語（スペイン）','Spanish (Spain)','Español','西班牙語（西班牙）','西班牙语（西班牙）','스페인어 (스페인)','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('es-la','Spanish (Latin America)','es','スペイン語（ラテンアメリカ）','Spanish (Latin America)','Español (América Latina)','西班牙語（拉丁美洲）','西班牙语（拉丁美洲）','스페인어 (라틴 아메리카)','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('ko','Korean','kr','韓国語','Korean','Coreano','韓語','韩语','한국어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('fr','French','fr','フランス語','French','Francés','法文','法文','프랑스어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('fr-ca','French (Canada)','fr','フランス語（カナダ）','French (Canada)','Francés (Canadá)','法語（加拿大）','法语（加拿大）','프랑스어 (캐나다)','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('id','Indonesian','id','インドネシア語','Indonesian','Indonesio','印度尼西亞','印度尼西亚','인도네시아어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('it','Italian','it','イタリア語','Italian','Italiano','義大利文','义大利文','이태리어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('ja','Japanese','jp','日本語','Japanese','Japonés','日本','日本','일본어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('ms','Malay','my','マレー語','Malay','Malayo','馬來語','马来语','말레이어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('nl','Dutch','nl','オランダ語','Dutch','Holandés','荷蘭語','荷兰语','네덜란드','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('pt','Portuguese (Europe)','pt','ポルトガル語（ヨーロッパ）','Portuguese (Europe)','Portugués (Europa)','葡萄牙語（歐洲）','葡萄牙语（欧洲）','포르투갈어 (유럽)','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('pt-br','Portuguese (Brazil)','pt','ポルトガル語（ブラジル）','Portuguese (Brazil)','Portugués (Brasil)','葡萄牙語（巴西）','葡萄牙语（巴西）','포르투갈어 (브라질)','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('th','Thai','th','タイ語','Thai','Tailandés','泰國','泰国','타이어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('tl','Tagalog','ph','タガログ語','Tagalog','Tagalo','他加祿語','他加禄语','타갈로그어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('tr','Turkish','tr','トルコ語','Turkish','Turco','土耳其','土耳其','터키어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('zh-hk','Chinese (Hong Kong)','cn','中国語（香港）','Chinese (Hong Kong)','Chino (Hong Kong)','中文（香港）','中文（香港）','중국어 (홍콩)','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('zh-tw','Chinese (Traditional)','cn','中国語（繁体字）','Chinese (Traditional)','Chino (tradicional)','繁體中文','繁體中文','중국어 (번체)','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('ru','Russian','ru','ロシア語','Russian','Ruso','俄語','俄语','러시아어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('sv','Swedish','se','スウェーデン語','Swedish','Sueco','瑞典','瑞典','스웨덴어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('bg','Bulgarian','bg','ブルガリア語','Bulgarian','Búlgaro','保加利亞語','保加利亚语','불가리아어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('cs','Czech','cz','チェコ語','Czech','Checo','捷克文','捷克文','체코 어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('da','Danish','dk','デンマーク語','Danish','Danés','丹麥文','丹麦文','덴마크어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('el','Greek','gr','ギリシャ語','Greek','Griego','希臘語','希腊语','그리스어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('en-gb','English (British)','en','英語（イギリス）','English (British)','Inglés (británico)','英語（英國）','英语（英国）','영어 (영국)','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('fi','Finnish','fi','フィンランド語','Finnish','Finlandés','芬蘭','芬兰','핀란드어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('he','Hebrew','il','ヘブライ語','Hebrew','Hebreo','希伯來語','希伯来语','히브리어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('hu','Hungarian','hu','ハンガリー語','Hungarian','Húngaro','匈牙利','匈牙利','헝가리어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('no','Norwegian','no','ノルウェー語','Norwegian','Noruego','挪威','挪威','노르웨이어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('pl','Polish','pl','ポーランド語','Polish','Polaco','拋光','抛光','폴란드어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('ro','Romanian','ro','ルーマニア語','Romanian','Rumano','羅馬尼亞語','罗马尼亚语','루마니아어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('vi','Vietnamese','vn','ベトナム語','Vietnamese','Vietnamita','越南文','越南文','베트남어','1');
insert into application_language(lc,language,flagId,japanese,english,spanish,chineseTra,chineseSim,korean,validFlag)Values('zh','Chinese (Simplified)','ch','中国語（簡体字）','Chinese (Simplified)','Chino (simplificado)','簡體中文','简体中文','중국어 (간체)','1');

insert into application_displayLanguage(language,listname)Values('English','English');
insert into application_displayLanguage(language,listname)Values('Japanese','日本語');
insert into application_displayLanguage(language,listname)Values('Spanish','Español');
insert into application_displayLanguage(language,listname)Values('ChineseTra','繁體中文');
insert into application_displayLanguage(language,listname)Values('ChineseSim','简体中文');
insert into application_displayLanguage(language,listname)Values('Korean','한국');

