# Generated by Django 3.0.8 on 2020-07-15 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, null=True)),
                ('userEmail', models.CharField(max_length=300, null=True)),
                ('userCreditCardNumber', models.CharField(max_length=20, null=True)),
                ('userLanguage', models.CharField(max_length=20, null=True)),
                ('validFlag', models.SmallIntegerField(null=True)),
            ],
            options={
                'index_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workTitle', models.CharField(max_length=100, null=True)),
                ('WordsOriginal', models.CharField(max_length=300, null=True)),
                ('lc_src', models.CharField(max_length=3, null=True)),
                ('lc_tgt', models.CharField(max_length=3, null=True)),
                ('progress', models.IntegerField(null=True)),
                ('createdDate', models.DateField(null=True)),
                ('numberofchar', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
            options={
                'index_together': {('user',)},
            },
        ),
    ]
