# Generated by Django 3.0.8 on 2020-07-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='WordsOriginal',
            new_name='wordsOriginal',
        ),
        migrations.AddField(
            model_name='user',
            name='defaultLcSrc',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='defaultLcTgt',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
