# Generated by Django 3.0.8 on 2020-07-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200723_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc', models.CharField(max_length=3, null=True)),
                ('language', models.CharField(max_length=50, null=True)),
                ('flagId', models.CharField(max_length=3, null=True)),
                ('japanese', models.CharField(max_length=30, null=True)),
                ('english', models.CharField(max_length=30, null=True)),
                ('spanish', models.CharField(max_length=30, null=True)),
                ('chinese', models.CharField(max_length=30, null=True)),
                ('korean', models.CharField(max_length=30, null=True)),
            ],
            options={
                'index_together': {('lc',)},
            },
        ),
    ]
