# Generated by Django 3.0.8 on 2020-07-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='chinese',
            new_name='chineseSim',
        ),
        migrations.AddField(
            model_name='language',
            name='chineseTra',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
