# Generated by Django 3.0.8 on 2020-07-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200723_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flagId',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='lc',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
