# Generated by Django 3.0.8 on 2020-07-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_translationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationhistory',
            name='createdDate',
            field=models.DateField(null=True),
        ),
    ]
