# Generated by Django 3.0.8 on 2020-08-01 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, null=True)),
                ('userEmail', models.CharField(max_length=300, null=True)),
                ('userCreditCardNumber', models.CharField(max_length=20, null=True)),
                ('userLanguage', models.CharField(max_length=20, null=True)),
                ('defaultLcSrc', models.CharField(max_length=5, null=True)),
                ('defaultLcTgt', models.CharField(max_length=5, null=True)),
                ('validFlag', models.SmallIntegerField(null=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'index_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=100, null=True)),
                ('backgroundcolor', models.CharField(max_length=8, null=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
            options={
                'index_together': {('user_id',)},
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workTitle', models.CharField(max_length=100, null=True)),
                ('wordsOriginal', models.TextField(null=True)),
                ('lc_src', models.CharField(max_length=5, null=True)),
                ('lc_tgt', models.CharField(max_length=5, null=True)),
                ('progress', models.IntegerField(null=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('numberofchar', models.IntegerField(null=True)),
                ('wordsTranslated', models.TextField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
            options={
                'index_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beforeTranslation', models.TextField(null=True)),
                ('afterTranslation', models.TextField(null=True)),
                ('TranslationType', models.CharField(max_length=10, null=True)),
                ('jobid', models.CharField(max_length=20, null=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('work', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.Works')),
            ],
            options={
                'get_latest_by': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc', models.CharField(max_length=5, null=True)),
                ('language', models.CharField(max_length=50, null=True)),
                ('flagId', models.CharField(max_length=5, null=True)),
                ('japanese', models.CharField(max_length=30, null=True)),
                ('english', models.CharField(max_length=30, null=True)),
                ('spanish', models.CharField(max_length=30, null=True)),
                ('chineseTra', models.CharField(max_length=30, null=True)),
                ('chineseSim', models.CharField(max_length=30, null=True)),
                ('korean', models.CharField(max_length=30, null=True)),
                ('validFlag', models.SmallIntegerField(null=True)),
            ],
            options={
                'index_together': {('lc',)},
            },
        ),
        migrations.CreateModel(
            name='WorkUserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.UserTag')),
                ('work', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.Works')),
            ],
            options={
                'index_together': {('work_id',)},
            },
        ),
    ]
