# Generated by Django 3.0.8 on 2020-08-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationhistory',
            name='historyNum',
            field=models.IntegerField(null=True),
        ),
    ]
