# Generated by Django 3.0.8 on 2020-08-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_translationhistory_historynum'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationhistory',
            name='deleteFlag',
            field=models.SmallIntegerField(null=True),
        ),
    ]
