# Generated by Django 3.0.8 on 2020-08-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20200813_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username2',
            field=models.CharField(blank=True, max_length=30, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
