# Generated by Django 3.0.8 on 2020-08-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200813_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username2',
            field=models.CharField(default='username', max_length=30, verbose_name='User name'),
        ),
    ]
