# Generated by Django 3.0.8 on 2020-08-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20200813_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
