# Generated by Django 3.0.8 on 2020-08-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username2',
            field=models.CharField(default='', max_length=30, verbose_name='User name'),
        ),
    ]
