# Generated by Django 3.0.8 on 2020-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_usertag_validflg'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='eta',
            field=models.DateTimeField(null=True),
        ),
    ]
