# Generated by Django 3.0.8 on 2020-08-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
