# Generated by Django 3.0.8 on 2020-08-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_userglossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userglossary',
            name='lc_src',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userglossary',
            name='lc_tgt',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
