# Generated by Django 3.0.8 on 2020-08-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20200825_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userglossary',
            name='fileid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
