# Generated by Django 3.0.8 on 2020-07-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200723_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beforeTranslationWithTags', models.TextField(null=True)),
                ('beforeTranslation', models.TextField(null=True)),
                ('afterTranslation', models.TextField(null=True)),
                ('TranslationType', models.SmallIntegerField(null=True)),
                ('jobid', models.CharField(max_length=20, null=True)),
                ('work', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.Works')),
            ],
            options={
                'index_together': {('id',)},
            },
        ),
    ]
