# Generated by Django 3.0.8 on 2020-07-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_translationhistory_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=100, null=True)),
                ('backgroundcolor', models.CharField(max_length=8, null=True)),
                ('createdDate', models.DateField(null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
            options={
                'index_together': {('user_id',)},
            },
        ),
        migrations.CreateModel(
            name='WorkUserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(null=True)),
                ('tag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.UserTag')),
                ('work', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.Works')),
            ],
            options={
                'index_together': {('work_id',)},
            },
        ),
    ]
