# Generated by Django 3.0.8 on 2020-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_usertag_workusertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='wordsOriginal',
            field=models.TextField(null=True),
        ),
    ]
