# Generated by Django 3.0.8 on 2020-07-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200728_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='defaultLcSrc',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='defaultLcTgt',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='lc_src',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='lc_tgt',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
