# Generated by Django 3.0.8 on 2020-07-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20200728_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='validFlag',
            field=models.SmallIntegerField(null=True),
        ),
    ]
