# Generated by Django 3.0.8 on 2020-07-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_language_validflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='wordsTranslated',
            field=models.TextField(null=True),
        ),
    ]
