# Generated by Django 3.0.8 on 2020-08-01 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20200731_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationhistory',
            options={'get_latest_by': ['id']},
        ),
        migrations.AddField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='works',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workusertag',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterIndexTogether(
            name='translationhistory',
            index_together=set(),
        ),
    ]
